apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque # Standard type for user-defined secrets
data:
  # Base64 encoded password for MYSQL_ROOT_PASSWORD
  # Use: echo -n 'YourPassword' | base64
  mysql-root-password: cGFzc3dvcmQ= # Example encoded value
