apiVersion: v1
kind: Pod
metadata:
  name: test-pod-s3-storage
spec:
  containers:
    - name: s3-writer-container
      image: busybox
      command: ["/bin/sh", "-c"]
      args: ["echo 'S3 Data Test: $(date)' > /s3data/testfile.txt; sleep 3600"]
      volumeMounts:
        - name: s3-volume
          mountPath: /s3data # Mount point inside the container
  volumes:
    - name: s3-volume
      persistentVolumeClaim:
        claimName: my-s3-pvc
