apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-s3-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi # Request size must match or be smaller than the PV's capacity
  storageClassName: s3-mountpoint-sc
