apiVersion: v1
kind: Pod
metadata:
  name: test-pod-ebs-storage
spec:
  containers:
    - name: writer-container
      image: busybox
      command: ["/bin/sh", "-c"]
      args: ["echo 'Data persisted on AWS EBS' > /mnt/ebs/test.txt; sleep 3600"]
      volumeMounts:
        - name: ebs-volume
          mountPath: /mnt/ebs # Mount point inside the container
  volumes:
    - name: ebs-volume
      persistentVolumeClaim:
        claimName: my-ebs-pvc # References the PVC
